"""Shareable provenance certificate for a tracked experiment.

Turns :meth:`quantproto.tracker.experiment.Experiment.report` into a
self-contained HTML page — the answer to what allocators say they can't get:
proof of *how many configurations were actually tried*, backed by a
tamper-evident chain, not a self-reported number in a pitch deck.

Reuses the score/stats/PBO/flags rendering from
:mod:`quantproto.dashboard.report_html` and adds the research-provenance
block on top.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from quantproto.dashboard.report_html import (
    _CSS,
    _VERDICT_STYLE,
    _esc,
    _fmt,
    _component_rows,
    _stat_rows,
    _pbo_section,
    _cost_curve_svg,
    _flags_section,
    _checklist_section,
)

_PROVENANCE_CSS = """
.prov { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
        gap: 14px; }
.prov div { text-align: left; }
.prov .v { font-size: 22px; font-weight: 700; }
.prov .l { font-size: 11px; text-transform: uppercase; letter-spacing: .06em;
           color: #64748b; margin-top: 2px; }
.chainbadge { display: inline-flex; align-items: center; gap: 6px;
              padding: 4px 12px; border-radius: 999px; font-weight: 600; font-size: 13px; }
"""


def render_certificate_html(report: dict[str, Any]) -> str:
    """Render an experiment's robustness report as a provenance certificate."""
    exp = report.get("experiment") or {}
    verdict = str(report.get("verdict", "fragile"))
    color, verdict_label, verdict_blurb = _VERDICT_STYLE.get(
        verdict, ("#94a3b8", verdict or "Unknown", "")
    )
    score = report.get("score")
    headline = report.get("headline") or verdict_blurb
    chain_ok = bool(exp.get("chain_valid"))
    chain_color = "#22c55e" if chain_ok else "#ef4444"
    chain_label = "Chain intact — trial count is honest" if chain_ok else "CHAIN BROKEN — do not trust this count"
    generated = datetime.now(timezone.utc).isoformat(timespec="seconds")

    best_params = ", ".join(f"{k}={v}" for k, v in (exp.get("best_params") or {}).items()) or "—"

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>QuantProto — Research Provenance Certificate — {_esc(exp.get('name', ''))}</title>
<style>{_CSS}{_PROVENANCE_CSS}</style>
</head>
<body><div class="wrap">
<h1>QuantProto — Research Provenance Certificate</h1>
<p class="meta">Experiment "{_esc(exp.get('name', ''))}" · generated {_esc(generated)}</p>

<div class="card scorebox">
  <div class="score" style="color:{color}">{_fmt(score)}<small> /100</small></div>
  <div>
    <span class="badge" style="background:{color}22;color:{color}">{verdict_label}</span>
    <p class="headline">{_esc(headline)}</p>
  </div>
</div>

<h2>Research provenance</h2>
<div class="card">
  <div class="prov">
    <div><div class="v">{_fmt(exp.get('n_runs'))}</div><div class="l">Runs logged</div></div>
    <div><div class="v">{_fmt(exp.get('n_configs'))}</div><div class="l">Distinct configs</div></div>
    <div><div class="v" style="font-size:15px">{_esc(best_params)}</div><div class="l">Best config</div></div>
  </div>
  <p style="margin-top:16px">
    <span class="chainbadge" style="background:{chain_color}22;color:{chain_color}">{chain_label}</span>
  </p>
  <p class="meta" style="margin-top:10px">Every configuration tried was recorded into a
  hash-chained ledger at the moment it was run, in order, before results were known. The
  trial count above — which drives the Deflated Sharpe and PBO corrections — is measured
  from that ledger, not self-reported.</p>
</div>

<h2>Score components</h2>
<div class="card"><table>{_component_rows(report.get('components') or {})}</table></div>

<h2>Key statistics</h2>
<div class="card"><table>{_stat_rows(report.get('statistics') or {})}</table></div>

{_pbo_section(report.get('pbo'))}
{_cost_curve_svg(report.get('cost_curve'))}
{_flags_section(report.get('red_flags') or [])}
{_checklist_section(report.get('checklist') or [])}

<p class="footer">Generated by QuantProto — backtest-integrity auditor. This certificate
reflects the research process at the time of generation; verify the chain independently
with <code>qp verify {_esc(exp.get('name', ''))}</code> before relying on it.</p>
</div></body></html>"""
